
version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  server:
    build: ./server
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:6434261@localhost:5432/marketing?schema=public
      - CLIENT_BASE_URL=http://web:3000
      - SERVER_BASE_URL=http://server:4000
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=change-me-super-secret
    ports: ["4000:4000"]
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 10

  web:
    build: ./web
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://server:4000
    ports: ["3000:3000"]
    depends_on:
      server:
        condition: service_healthy
